### ISSUE TITLE
SCC getRules api call does not return remediations

### ISSUE THREAD

**Issue by SergioGabeteSysdig** [IBM/scc-go-sdk#144]
**Describe the bug**
The API Call to get the rules is not returning the remediation

**To Reproduce**
List the steps that can be used to demonstrate the bug.  Include the name of the service and operation that you're trying to invoke, if applicable.  Be sure to describe any relevant info regarding parameter values used with your API invocation.

**Expected behavior**

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version [e.g. 1.2.1]
 - Go Version [e.g. 1.12.15]
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**
Were you able to avoid the problem by changing your application code slightly?

**Comment by tyao117** [comment]
Released a new version: https://github.com/IBM/scc-go-sdk/releases/tag/v5.3.0. @SergioGabeteSysdig can you verify?
