### ISSUE TITLE
Pipeline failing on "publishing code coverage report to codeclimate"

### ISSUE THREAD

**Issue by tyao117** [IBM/scc-go-sdk#71]
**Describe the bug**
Code Pipeline to verify the changes of the code is broken due to:
```
Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
```
LINK: https://github.com/IBM/scc-go-sdk/runs/4781084363?check_suite_focus=true#step:4:35
~PR request: https://github.com/IBM/scc-go-sdk/pull/70~

**To Reproduce**
- Make a PR request against the repo.
- Submit the PR to trigger pipeline.

**Expected behavior**
Not having  `CC_TEST_REPORTER_ID` as a error

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version: `1.0.0`
 - Go Version: `go version go1.17.5 darwin/amd64` <-- local
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**
Were you able to avoid the problem by changing your application code slightly?

**Comment by gary1998** [comment]
@tyao117  This is not an issue, this is expected behaviour. Github Actions does not expose repo secrets to any forked repo. So, whenever pipeline runs for any commit inside the forked repo or any PR from forked repo to main repo, secrets are always missing….
Correct process is:
- Get a non-main branch in main repo and start working inside it
- Then, raise PR from non-main branch to main branch

**Comment by gary1998** [comment]
Also, can you check the `Verify` stage of pipeline too as it is failing and it doesn't require any repo secret.

**Comment by tyao117** [comment]
@gary1998 Couldn't push the branch onto the repo:
```
(.direnv)➜  scc-go-sdk git:(notify_update) ✗ git push --set-upstream origin notify_update
remote: Permission to IBM/scc-go-sdk.git denied to tyao117.
fatal: unable to access 'https://github.com/IBM/scc-go-sdk.git/': The requested URL returned error: 403
```

**Comment by tyao117** [comment]
After @gary1998 gave me permission to write to the repo, I was able to write to the repo. Closing the issue.
